"""empty message

Revision ID: e37529d5647
Revises: 35a31843c73f
Create Date: 2019-09-30 11:40:04.000349

"""

# revision identifiers, used by Alembic.
revision = 'e37529d5647'
down_revision = '35a31843c73f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
